/**
 * payload-types.ts
 * 
 * Auto-generated types for Payload CMS collections.
 * These types are regenerated on every `next build` via payload.config.ts › typescript.outputFile.
 * Do NOT edit this file manually — changes will be overwritten on the next build.
 * 
 * Collections: Users, Posts, Categories, Media, Jobs, FormSubmissions
 */

/* eslint-disable @typescript-eslint/no-explicit-any */

export type PayloadRequest = {
  user?: User | null;
  [key: string]: any;
};

// ─── Media ───────────────────────────────────────────────────────────────────

export type Media = {
  id: string;
  alt: string;
  caption?: string | null;
  /** Populated by Cloudinary storage plugin */
  url?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  updatedAt: string;
  createdAt: string;
  // Cloudinary-specific fields added by payload-storage-cloudinary
  cloudinaryPublicId?: string | null;
  cloudinaryUrl?: string | null;
  cloudinaryResourceType?: string | null;
};

// ─── Categories ───────────────────────────────────────────────────────────────

export type Category = {
  id: string;
  title: string;
  slug: string;
  updatedAt: string;
  createdAt: string;
};

// ─── Users ────────────────────────────────────────────────────────────────────

export type User = {
  id: string;
  firstName: string;
  lastName: string;
  role: 'super-admin' | 'editor';
  email: string;
  updatedAt: string;
  createdAt: string;
};

// ─── Posts ────────────────────────────────────────────────────────────────────

export type Post = {
  id: string;
  title: string;
  slug: string;
  category: string | Category;
  heroImage: string | Media;
  excerpt?: string | null;
  readTime?: string | null;
  featured?: boolean | null;
  publishedDate: string;
  author?: string | null;
  authorRole?: string | null;
  /** Lexical rich-text content object */
  content: Record<string, any>;
  updatedAt: string;
  createdAt: string;
};

// ─── Jobs ─────────────────────────────────────────────────────────────────────

export type Job = {
  id: string;
  title: string;
  department: string;
  location: string;
  type: 'full-time' | 'part-time' | 'contract' | 'internship';
  /** Lexical rich-text job description */
  description?: Record<string, any> | null;
  applicationEmail: string;
  active?: boolean | null;
  updatedAt: string;
  createdAt: string;
};

// ─── FormSubmissions ──────────────────────────────────────────────────────────

export type FormSubmission = {
  id: string;
  formType: 'contact' | 'consultancy' | 'careers';
  name: string;
  email: string;
  phone?: string | null;
  subjectOrPosition?: string | null;
  message: string;
  updatedAt: string;
  createdAt: string;
};

// ─── Collection slugs ─────────────────────────────────────────────────────────

export type CollectionSlug =
  | 'users'
  | 'posts'
  | 'categories'
  | 'media'
  | 'jobs'
  | 'form-submissions';

// ─── Payload Config Types ─────────────────────────────────────────────────────

export interface Config {
  collections: {
    users: User;
    posts: Post;
    categories: Category;
    media: Media;
    jobs: Job;
    'form-submissions': FormSubmission;
  };
}
